name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          working_directory: latex
          texlive_version: 2024
          os: debian
          work_in_root_file_dir: true
          root_file: Chemistry_products.tex
